### ISSUE TITLE
Question about AFT integration

### ISSUE THREAD

**Issue by luigidifraiawork** [aws-samples/aws-network-hub-for-terraform#11]
Thank you for the material and networking pattern implemented in this repo.

As the root [README.md](../blob/main/README.md) file mentions:

> Perfect for a central networking hub account, potentially alongside Account Factory for Terraform

I thought to ask for your thoughts on the below. It's probably a long shot but I'd appreciate the feedback, even if it where along the lines of "don't ask here, go ask there instead".

1. Would you reckon it makes sense to implement the networking pattern directly as part of AFT account customizations?
2. If so, any thoughts on how to [access route tables](https://github.com/aws-samples/aws-network-hub-for-terraform/blob/main/example-spoke-vpc/data.tf#L16) from a spoke account within the AWS Organization using native AFT facilities?
3. Are you aware of anyone working on 1. already?

Thank you.

**Comment by aandsco** [comment]
Hi @luigidifraiawork 

I refactored the solution to work with a CT based LZ using AFT for account vending.

I created separate pipelines for each module with in the network hub account for development.

In the account customization is where i handled the VPC creation and any other links to the central networking.

**Comment by luigidifraiawork** [comment]
Hi @aandsco.

Thank you for taking the time to answer my question. At the time I tried, deploying the Network Hub as part of the AFT account customization pipeline was fine, but the account customization pipeline for a Spoke was erroring out as it could not assume the `${var.environment}_network_automation_role` role:
```
│ Error: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: c0895435-f03f-44fe-a5b8-0ec60c2e8e0d, api error AccessDenied: User: arn:aws:sts::<AFT account number>:assumed-role/AWSAFTAdmin/AWSAFT-Session is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<Network Hub account number>:role/prod_network_automation_role
```
The error refers to the role used by the second TF provider for the Spoke account customization: [provider.tf](https://github.com/aws-samples/aws-network-hub-for-terraform/blob/main/example-spoke-vpc/provider.tf#L25).

For both Hub and Spoke I used the same value for `var.environment`, i.e. `prod`.

Did you have this sort of issues when testing within the AFT account customization pipeline for Spokes?

Thanks again for taking the time!

Cheers,

Luigi

**Comment by aandsco** [comment]
A few changes are that var.environment isn’t set. I handled this by using custom fields to write a ssm param and a data source to read it instead.

the assume role issue is that your now using the AFT execution role so amending this should help. 

It took me a few days to fully decouple the hub services and get accounts vended with aft with fully transitive network and dns.

**Comment by luigidifraiawork** [comment]
Do you remember what changes you did to which role in each spoke account?

As far as I can tell, the _AWSAFTExecution_ role in each spoke account has the _AdministratorAccess_ (`arn:aws:iam::aws:policy/AdministratorAccess`) policy attached and there's no permission boundary set. The trust relationship trusts the entity as per below:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:sts::<AFT account number>:assumed-role/AWSAFTAdmin/AWSAFT-Session"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
The above trusted entity doesn't seem to be allowed to assume the `${var.environment}_network_automation_role` role (`arn:aws:iam::<Network Hub account number>:role/prod_network_automation_role`) in a vanilla AFT deployment? That's what the error message suggests. It doesn't even appear that the _AWSAFTExecution_ role is involved directly, based on the error.

I even tried to relax the trust relationship for the `${var.environment}_network_automation_role` role to be:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "sts:AssumeRole",
        }
    ]
}
```
But that didn't seem to help either. I could try again, I just want to make sure I am not missing any pre-requisite here.

**Comment by aandsco** [comment]
Var.environment doesn’t exist so you’ll need to source that a different way, I detailed how I did it above.

**Comment by aandsco** [comment]
The aft role has * but the automation role allows any role in the org with the tag automatiom = true

**Comment by aandsco** [comment]
It would be inefficient to add this, so use the aft-execution role in the network hub account

**Comment by luigidifraiawork** [comment]
> It would be inefficient to add this, so use the aft-execution role in the network hub account

Thank you for your help!
