### ISSUE TITLE
Example_spoke_vpc code not working

### ISSUE THREAD

**Issue by sathe06** [aws-samples/aws-network-hub-for-terraform#17]
HI @aandsco @jplock @luigidifraiawork 
I am re-using this code, Got struck at terraform plan for spoke_vpc.
I have successfully created on network-hub on prod environment. Similarly trying to create spoke-vpc facing below issue.
```
 terraform plan
var.environment
  Deployment environment passed as argument or environment variable

  Enter a value: prod

var.network_hub_account_number
  network hub account number passed as argument or environment variable

  Enter a value: xxx

╷
│ Error: error reading EC2 Transit Gateway: no results found
│
│   with data.aws_ec2_transit_gateway.org_env,
│   on data.tf line 8, in data "aws_ec2_transit_gateway" "org_env":
│    8: data "aws_ec2_transit_gateway" "org_env" {
│
╵
╷
│ Error: no Route53 Resolver rules matched
│
│   with module.dns.data.aws_route53_resolver_rule.root_domain,
│   on modules/dns/data.tf line 6, in data "aws_route53_resolver_rule" "root_domain":
│    6: data "aws_route53_resolver_rule" "root_domain" {
│
╵
╷
│ Error: no matching EC2 VPC found
│
│   with module.dns.data.aws_vpc.selected,
│   on modules/dns/data.tf line 16, in data "aws_vpc" "selected":
│   16: data "aws_vpc" "selected" {
│
╵
╷
│ Error: no matching EC2 VPC found
│
│   with module.dns.data.aws_vpc.endpoint,
│   on modules/dns/data.tf line 24, in data "aws_vpc" "endpoint":
│   24: data "aws_vpc" "endpoint" {
│
╵
╷
│ Error: Error describing SSM parameter (/ipam/pool/id): ParameterNotFound:
│
│   with module.network.data.aws_ssm_parameter.ipam_pool,
│   on modules/network/data.tf line 4, in data "aws_ssm_parameter" "ipam_pool":
│    4: data "aws_ssm_parameter" "ipam_pool" {
```

Can you please suggest how to solve this issue.

**Comment by luigidifraiawork** [comment]
@sathe06 Did you enable RAM sharing?

**Comment by sathe06** [comment]
@luigidifraiawork 
No, we have disabled this feature

**Comment by luigidifraia** [comment]
@sathe06 Without RAM sharing enabled, the setup of the spoke cannot look up TGW resources in the Network hub account. You need to have RAM sharing enabled.

**Comment by rocki9satya** [comment]
> @sathe06 Without RAM sharing enabled, the setup of the spoke cannot look up TGW resources in the Network hub account. You need to have RAM sharing enabled.

Here we are not using multiple account ..there is only one account ..can we not tailor it to use without RAM sharing ...?

**Comment by aandsco** [comment]
@sathe06 this is a sample of how to configure and deploy a hub and spoke network topology using AWS organisations with in a multi account strategy.

You can take this sample code and use it as you wish.

There may be more suitable samples that deal with networking hub and spoke in a single account. 

But this solutions depends on have AWS Organizations set up with multiple accounts and having trusted access enabled for RAM. 

The error you are seeing is due to using the sample in a way in which it wasn’t intended.

**Comment by aandsco** [comment]
Closing issue as the use case was not intended for the sample.

**Comment by luigidifraia** [comment]
@sathe06 This is the AWS example you might want to follow in your mono-account scenario: https://github.com/aws-samples/hub-and-spoke-with-inspection-vpc-terraform
