### ISSUE TITLE
Example_spoke_vpc code not working again due to missing parameters

### ISSUE THREAD

**Issue by sathe06** [aws-samples/aws-network-hub-for-terraform#19]
HI @aandsco @jplock @luigidifraiawork 

We have enabled RAM sharing and testing this feature, got struck with this error.

│ Error: error updating EC2 Transit Gateway Attachment (tgw-attach-01f89f6f73a41a5fe) Route Table () association: error associating EC2 Transit Gateway Route Table () assoc
iation (tgw-attach-01f89f6f73a41a5fe): MissingParameter: Missing required parameter in request: TransitGatewayRouteTableId.
│       status code: 400, request id: ebc18aa5-c437-4afc-b417-d81f07a3938f
│
│   with module.network.aws_ec2_transit_gateway_vpc_attachment.vpc_endpoint,
│   on modules/network/vpc.tf line 77, in resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_endpoint":
│   77: resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_endpoint" {

```
  # module.network.aws_ec2_transit_gateway_vpc_attachment.vpc_endpoint will be created
  + resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_endpoint" {
      + appliance_mode_support                          = "disable"
      + dns_support                                     = "enable"
      + id                                              = (known after apply)
      + ipv6_support                                    = "enable"
      + subnet_ids                                      = (known after apply)
      + tags_all                                        = {
          + "Env"        = "prod"
          + "Owner"      = "WWPS"
          + "Product"    = "Network_Automation"
          + "Project_ID" = "12345"
        }
      + transit_gateway_default_route_table_association = true
      + transit_gateway_default_route_table_propagation = true
      + transit_gateway_id                              = "tgw-xxx"
      + vpc_id                                          = (known after apply)
      + vpc_owner_id                                    = (known after apply)
    }


```
Can you please suggest how to solve this issue.

**Comment by aandsco** [comment]
@sathe06 

From the previous issue you raised it appears the issues come from you changing the deployment substantially from the example code. 

If you deploy the hub and spoke without any code or environment changes this will have the desired effect.

Also ensure all variables are appropriately declared.

This sample does expect an advance level of knowledge and experience with AWS Organizations and AWS networking services such as TGW, Network Firewall etc.

**Comment by sathe06** [comment]
fix for this issue is 
line no 83 and 84 should be uncommented on this link.
https://github.com/aws-samples/aws-network-hub-for-terraform/blob/main/example-spoke-vpc/modules/network/vpc.tf

**Comment by aandsco** [comment]
@sathe06 that unfortunately isn’t a fix for your issue. 

Allowing default route table attachment and propagation can cause unwanted behaviour for any new vpc, you will either have no segregation of envs or have to retrospectively move them to specific TGW route tables.

As I said above it is a complex solution networking in a multi account solution with environment segregation.

**Comment by sathe06** [comment]
![image](https://user-images.githubusercontent.com/64068637/172006441-92bd75dc-ef97-450e-ba74-b4a88fbb4421.png)
these are the 4 vpc's found

**Comment by aandsco** [comment]
This solution does not cater for a spoke VPC in the central network hub. This breaks the separation of concerns at an organisational level that this sample addresses.

Whilst it has allowed you to deploy a spoke VPC into the central network hub by further deviating from the sample code this was never the intended use case. 

There are other AWS samples that deal with networking within a single account.
