### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by jplock** [aws-samples/aws-network-hub-for-terraform#5]
Would you accept a pull request to add IPv6 support? I know we can't route IPv6 through the Network Firewall because the Gateway Load Balancer doesn't yet support IPv6, but we could plumb everything else through.

**Comment by aandsco** [comment]
That sounds a great idea, I’m definetly interested

**Comment by jplock** [comment]
Would you be ok with the Amazon provided IPv6 space or would you want it to come from IPAM?

**Comment by aandsco** [comment]
PR created - closing issue
