### ISSUE TITLE
Inspection VPC: appliance_mode_support?

### ISSUE THREAD

**Issue by jplock** [aws-samples/aws-network-hub-for-terraform#8]
Does the [ec2_transit_gateway_vpc_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment) in the inspection_vpc need [appliance_mode_support](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment#appliance_mode_support) set to `enable`?

https://github.com/aws-samples/aws-network-hub-for-terraform/blob/main/modules/network_firewall_vpc/vpc.tf#L103

per https://aws.amazon.com/blogs/networking-and-content-delivery/centralized-inspection-architecture-with-aws-gateway-load-balancer-and-aws-transit-gateway/

**Comment by aandsco** [comment]
Hi,

I don't believe so, If/when i include GWLB into the pattern we will definitely. 

That being said i haven't found any documentation stating it doesn't need it either.

**Comment by jplock** [comment]
NFW uses GWLB which is why I was wondering.

**Comment by aandsco** [comment]
I’m wondering too, I’ve reached out to a specialist SA to ask the question.

**Comment by aandsco** [comment]
I have the answer, we should enable appliance mode support, I’ll get it added shortly.

thank you for the spot.

**Comment by aandsco** [comment]
appliance mode support added to inspection VPC - closing issue. Many thanks

**Comment by jplock** [comment]
👍
